apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kube-registry-proxy
  namespace: kube-system
  labels:
    app: kube-registry-proxy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kube-registry-proxy
    spec:
      hostNetwork: true
      containers:
      - name: registry-proxy
        image: gcr.io/google_containers/kube-registry-proxy:0.3
        env:
        - name: REGISTRY_HTTP_ADDR
          value: :5000
        - name: REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY
          value: /var/lib/registry
        volumeMounts:
        - name: image-store
          mountPath: /var/lib/registry
        ports:
        - containerPort: 5000
          protocol: TCP
      volumes:
      - name: image-store
        hostPath:
          path: /var/lib/registry
