#!/bin/bash

function git_branch() {
  git branch 2> /dev/null | cut -f2 -d\* -s | sed "s/^ /[/" | sed "s/$/]/"
}

function kubernetes_context() {
  echo "[$( kubectl config current-context 2>/dev/null )]"
}

export PS1='\W $(git_branch) $(kubernetes_context) $ '

function to() {
  arg="$1/$2"
  if [ "$1" == "c" ]; then arg="coldog"; fi
  cd $HOME/Workspace/src/github.com/$arg
}

alias com="git add -A && git commit -m"

export EDITOR="nvim"
alias vi="nvim"
alias vim="nvim"
set -o vi

export CFG_ROOT="$HOME/.config/config"
export GOPATH="$HOME/Workspace"
export PATH="$PATH:$GOPATH/bin:$CFG_ROOT/bin/:~/.bin/"

# Since I am using a non-POSIX locale this is needed so that sort produces reliable output.
export LC_ALL=C
export LC_ALL=C.UTF-8
export LANG=C.UTF-8

alias setclip="xclip -selection c"
alias getclip="xclip -selection c -o"

if [ -x "$(command -v bat)" ]; then
  alias cat="bat"
fi

# Rbenv:
export RBENV_ROOT="$CFG_ROOT/rbenv"
export PATH="$CFG_ROOT/rbenv/bin:$PATH"
eval "$(rbenv init -)"

# Pyenv:
export PYENV_ROOT="$CFG_ROOT/pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

# Goenv:
export GOENV_ROOT="$CFG_ROOT/goenv"
export PATH="$GOENV_ROOT/bin:$PATH"
eval "$(goenv init -)"

# Nvm:
export NVM_DIR="$CFG_ROOT/nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Rust:
export PATH="$PATH:/home/colin/.cargo/bin"

# Source additional laptop specific.
if [ -f ~/.config/bash_added ]; then
  source ~/.config/bash_added
fi
